name: DevOps CI/CD

on:
  push:
    branches:
      - main
env:
  DOCKER_REGISTRY: docker.io

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          tags: ${{ env.DOCKER_REGISTRY }}/devops-ci-cd:${{ github.sha }}
          outputs: type=docker,dest=/tmp/${{ github.sha }}.tar
          context: .
          file: apps/api/Dockerfile
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}
          path: /tmp/${{ github.sha }}.tar
          
      
  container-scan:
    runs-on: ubuntu-latest
    needs: build
      
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.sha }}
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/${{ github.sha }}.tar

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ env.DOCKER_REGISTRY }}/devops-ci-cd:${{ github.sha }}
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"